// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Describes violations in a client request. This error type focuses on the
/// syntactic aspects of the request.
public struct BadRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Describes all violations in a client request.
  public var fieldViolations: [BadRequest.FieldViolation] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BadRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BadRequest().with { $0.fieldViolations = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let fieldViolations = CodingKeys(stringValue: "fieldViolations")

    static let _knownKeys: Set<Swift.String> = [
      "fieldViolations"
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [BadRequest.FieldViolation].self, forKey: .fieldViolations)
    {
      self.fieldViolations = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.fieldViolations, forKey: .fieldViolations)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A message type used to describe a single bad request field.
  public struct FieldViolation: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// A path that leads to a field in the request body. The value will be a
    /// sequence of dot-separated identifiers that identify a protocol buffer
    /// field.
    ///
    /// Consider the following:
    ///
    ///     message CreateContactRequest {
    ///       message EmailAddress {
    ///         enum Type {
    ///           TYPE_UNSPECIFIED = 0;
    ///           HOME = 1;
    ///           WORK = 2;
    ///         }
    ///
    ///         optional string email = 1;
    ///         repeated EmailType type = 2;
    ///       }
    ///
    ///       string full_name = 1;
    ///       repeated EmailAddress email_addresses = 2;
    ///     }
    ///
    /// In this example, in proto `field` could take one of the following values:
    ///
    /// * `full_name` for a violation in the `full_name` value
    /// * `email_addresses[0].email` for a violation in the `email` field of the
    ///   first `email_addresses` message
    /// * `email_addresses[2].type[1]` for a violation in the second `type`
    ///   value in the third `email_addresses` message.
    ///
    /// In JSON, the same values are represented as:
    ///
    /// * `fullName` for a violation in the `fullName` value
    /// * `emailAddresses[0].email` for a violation in the `email` field of the
    ///   first `emailAddresses` message
    /// * `emailAddresses[2].type[1]` for a violation in the second `type`
    ///   value in the third `emailAddresses` message.
    public var field: Swift.String = Swift.String()

    /// A description of why the request element is bad.
    public var description: Swift.String = Swift.String()

    /// The reason of the field-level error. This is a constant value that
    /// identifies the proximate cause of the field-level error. It should
    /// uniquely identify the type of the FieldViolation within the scope of the
    /// google.rpc.ErrorInfo.domain. This should be at most 63
    /// characters and match a regular expression of `[A-Z][A-Z0-9_]+[A-Z0-9]`,
    /// which represents UPPER_SNAKE_CASE.
    public var reason: Swift.String = Swift.String()

    /// Provides a localized error message for field-level errors that is safe to
    /// return to the API consumer.
    public var localizedMessage: LocalizedMessage? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `FieldViolation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FieldViolation().with { $0.field = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let field = CodingKeys(stringValue: "field")
      static let description = CodingKeys(stringValue: "description")
      static let reason = CodingKeys(stringValue: "reason")
      static let localizedMessage = CodingKeys(stringValue: "localizedMessage")

      static let _knownKeys: Set<Swift.String> = [
        "field",
        "description",
        "reason",
        "localizedMessage",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .field) {
        self.field = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
        self.description = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .reason) {
        self.reason = value
      }
      self.localizedMessage = try container.decodeIfPresent(
        LocalizedMessage.self, forKey: .localizedMessage)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.field, forKey: .field)
      try container.encode(self.description, forKey: .description)
      try container.encode(self.reason, forKey: .reason)
      try container.encodeIfPresent(self.localizedMessage, forKey: .localizedMessage)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.rpc.BadRequest.FieldViolation"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.rpc.BadRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
