// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The canonical error codes for gRPC APIs.
///
///
/// Sometimes multiple error codes may apply.  Services should return
/// the most specific error code that applies.  For example, prefer
/// `OUT_OF_RANGE` over `FAILED_PRECONDITION` if both codes apply.
/// Similarly prefer `NOT_FOUND` or `ALREADY_EXISTS` over `FAILED_PRECONDITION`.
public enum Code: Codable, Equatable, Sendable {
  case ok
  case cancelled
  case unknown
  case invalidArgument
  case deadlineExceeded
  case notFound
  case alreadyExists
  case permissionDenied
  case resourceExhausted
  case failedPrecondition
  case aborted
  case outOfRange
  case unimplemented
  case `internal`
  case unavailable
  case dataLoss
  case unauthenticated
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .ok
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .ok: return 0
    case .cancelled: return 1
    case .unknown: return 2
    case .invalidArgument: return 3
    case .deadlineExceeded: return 4
    case .notFound: return 5
    case .alreadyExists: return 6
    case .permissionDenied: return 7
    case .resourceExhausted: return 8
    case .failedPrecondition: return 9
    case .aborted: return 10
    case .outOfRange: return 11
    case .unimplemented: return 12
    case .`internal`: return 13
    case .unavailable: return 14
    case .dataLoss: return 15
    case .unauthenticated: return 16
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: String? {
    switch self {
    case .ok: return "OK"
    case .cancelled: return "CANCELLED"
    case .unknown: return "UNKNOWN"
    case .invalidArgument: return "INVALID_ARGUMENT"
    case .deadlineExceeded: return "DEADLINE_EXCEEDED"
    case .notFound: return "NOT_FOUND"
    case .alreadyExists: return "ALREADY_EXISTS"
    case .permissionDenied: return "PERMISSION_DENIED"
    case .resourceExhausted: return "RESOURCE_EXHAUSTED"
    case .failedPrecondition: return "FAILED_PRECONDITION"
    case .aborted: return "ABORTED"
    case .outOfRange: return "OUT_OF_RANGE"
    case .unimplemented: return "UNIMPLEMENTED"
    case .`internal`: return "INTERNAL"
    case .unavailable: return "UNAVAILABLE"
    case .dataLoss: return "DATA_LOSS"
    case .unauthenticated: return "UNAUTHENTICATED"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
  public init(stringValue: String) {
    switch stringValue {
    case "OK": self = .ok
    case "CANCELLED": self = .cancelled
    case "UNKNOWN": self = .unknown
    case "INVALID_ARGUMENT": self = .invalidArgument
    case "DEADLINE_EXCEEDED": self = .deadlineExceeded
    case "NOT_FOUND": self = .notFound
    case "ALREADY_EXISTS": self = .alreadyExists
    case "PERMISSION_DENIED": self = .permissionDenied
    case "UNAUTHENTICATED": self = .unauthenticated
    case "RESOURCE_EXHAUSTED": self = .resourceExhausted
    case "FAILED_PRECONDITION": self = .failedPrecondition
    case "ABORTED": self = .aborted
    case "OUT_OF_RANGE": self = .outOfRange
    case "UNIMPLEMENTED": self = .unimplemented
    case "INTERNAL": self = .`internal`
    case "UNAVAILABLE": self = .unavailable
    case "DATA_LOSS": self = .dataLoss
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .ok
    case 1: self = .cancelled
    case 2: self = .unknown
    case 3: self = .invalidArgument
    case 4: self = .deadlineExceeded
    case 5: self = .notFound
    case 6: self = .alreadyExists
    case 7: self = .permissionDenied
    case 16: self = .unauthenticated
    case 8: self = .resourceExhausted
    case 9: self = .failedPrecondition
    case 10: self = .aborted
    case 11: self = .outOfRange
    case 12: self = .unimplemented
    case 13: self = .`internal`
    case 14: self = .unavailable
    case 15: self = .dataLoss
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .ok: return try container.encode(0)
    case .cancelled: return try container.encode(1)
    case .unknown: return try container.encode(2)
    case .invalidArgument: return try container.encode(3)
    case .deadlineExceeded: return try container.encode(4)
    case .notFound: return try container.encode(5)
    case .alreadyExists: return try container.encode(6)
    case .permissionDenied: return try container.encode(7)
    case .resourceExhausted: return try container.encode(8)
    case .failedPrecondition: return try container.encode(9)
    case .aborted: return try container.encode(10)
    case .outOfRange: return try container.encode(11)
    case .unimplemented: return try container.encode(12)
    case .`internal`: return try container.encode(13)
    case .unavailable: return try container.encode(14)
    case .dataLoss: return try container.encode(15)
    case .unauthenticated: return try container.encode(16)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
