// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// The canonical error codes for gRPC APIs.
///
///
/// Sometimes multiple error codes may apply.  Services should return
/// the most specific error code that applies.  For example, prefer
/// `OUT_OF_RANGE` over `FAILED_PRECONDITION` if both codes apply.
/// Similarly prefer `NOT_FOUND` or `ALREADY_EXISTS` over `FAILED_PRECONDITION`.
public enum Code: Int, Codable, Equatable {
  case ok = 0
  case cancelled = 1
  case unknown = 2
  case invalidArgument = 3
  case deadlineExceeded = 4
  case notFound = 5
  case alreadyExists = 6
  case permissionDenied = 7
  case resourceExhausted = 8
  case failedPrecondition = 9
  case aborted = 10
  case outOfRange = 11
  case unimplemented = 12
  case `internal` = 13
  case unavailable = 14
  case dataLoss = 15
  case unauthenticated = 16

  public init() {
    self = .ok
  }

  public var stringValue: String {
    switch self {
    case .ok: return "OK"
    case .cancelled: return "CANCELLED"
    case .unknown: return "UNKNOWN"
    case .invalidArgument: return "INVALID_ARGUMENT"
    case .deadlineExceeded: return "DEADLINE_EXCEEDED"
    case .notFound: return "NOT_FOUND"
    case .alreadyExists: return "ALREADY_EXISTS"
    case .permissionDenied: return "PERMISSION_DENIED"
    case .resourceExhausted: return "RESOURCE_EXHAUSTED"
    case .failedPrecondition: return "FAILED_PRECONDITION"
    case .aborted: return "ABORTED"
    case .outOfRange: return "OUT_OF_RANGE"
    case .unimplemented: return "UNIMPLEMENTED"
    case .`internal`: return "INTERNAL"
    case .unavailable: return "UNAVAILABLE"
    case .dataLoss: return "DATA_LOSS"
    case .unauthenticated: return "UNAUTHENTICATED"
    }
  }

  public init?(stringValue: String) {
    switch stringValue {
    case "OK": self = .ok
    case "CANCELLED": self = .cancelled
    case "UNKNOWN": self = .unknown
    case "INVALID_ARGUMENT": self = .invalidArgument
    case "DEADLINE_EXCEEDED": self = .deadlineExceeded
    case "NOT_FOUND": self = .notFound
    case "ALREADY_EXISTS": self = .alreadyExists
    case "PERMISSION_DENIED": self = .permissionDenied
    case "UNAUTHENTICATED": self = .unauthenticated
    case "RESOURCE_EXHAUSTED": self = .resourceExhausted
    case "FAILED_PRECONDITION": self = .failedPrecondition
    case "ABORTED": self = .aborted
    case "OUT_OF_RANGE": self = .outOfRange
    case "UNIMPLEMENTED": self = .unimplemented
    case "INTERNAL": self = .`internal`
    case "UNAVAILABLE": self = .unavailable
    case "DATA_LOSS": self = .dataLoss
    default: return nil
    }
  }
}
