// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudWkt

/// Describes additional debugging info.
public struct DebugInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The stack trace entries indicating where the error occurred.
  public var stackEntries: [String]

  /// Additional debugging information provided by the server.
  public var detail: String

  /// Initialize a new instance of `DebugInfo`.
  public init(
    stackEntries: [String] = [],
    detail: String = String(),
  ) {
    self.stackEntries = stackEntries
    self.detail = detail
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.rpc.DebugInfo" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
