// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudWkt

/// Provides links to documentation or for performing an out of band action.
///
/// For example, if a quota check failed with an error indicating the calling
/// project hasn't enabled the accessed service, this can contain a URL pointing
/// directly to the right place in the developer console to flip the bit.
public struct Help: Codable, Equatable {
  /// URL(s) pointing to additional information on handling the current error.
  public var links: [Help.Link]

  /// Initialize a new instance of `Help`.
  public init(
    links: [Help.Link] = [],
  ) {
    self.links = links
  }

  /// Describes a URL link.
  public struct Link: Codable, Equatable {
    /// Describes what the link offers.
    public var description: String

    /// The URL of the link.
    public var url: String

    /// Initialize a new instance of `Link`.
    public init(
      description: String = String(),
      url: String = String(),
    ) {
      self.description = description
      self.url = url
    }
  }
}
