// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

public import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Represents an HTTP response.
public struct HttpResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The HTTP status code, such as 200 or 404.
  public var status: Swift.Int32 = Swift.Int32()

  /// The HTTP reason phrase, such as "OK" or "Not Found".
  public var reason: Swift.String = Swift.String()

  /// The HTTP response headers. The ordering of the headers is significant.
  /// Multiple headers with the same key may present for the response.
  public var headers: [HttpHeader] = []

  /// The HTTP response body. If the body is not expected, it should be empty.
  public var body: Foundation.Data = Foundation.Data()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `HttpResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HttpResponse().with { $0.status = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let status = CodingKeys(stringValue: "status")
    static let reason = CodingKeys(stringValue: "reason")
    static let headers = CodingKeys(stringValue: "headers")
    static let body = CodingKeys(stringValue: "body")

    static let _knownKeys: Set<Swift.String> = [
      "status",
      "reason",
      "headers",
      "body",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .status) {
      self.status = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .reason) {
      self.reason = value
    }
    if let value = try container.decodeIfPresent([HttpHeader].self, forKey: .headers) {
      self.headers = value
    }
    if let value = try container.decodeIfPresent(Foundation.Data.self, forKey: .body) {
      self.body = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.status, forKey: .status)
    try container.encode(self.reason, forKey: .reason)
    try container.encode(self.headers, forKey: .headers)
    try container.encode(self.body, forKey: .body)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.rpc.HttpResponse"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
