// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudWkt

/// Represents an HTTP response.
public struct HttpResponse: Codable, Equatable {
  /// The HTTP status code, such as 200 or 404.
  public var status: Int32

  /// The HTTP reason phrase, such as "OK" or "Not Found".
  public var reason: String

  /// The HTTP response headers. The ordering of the headers is significant.
  /// Multiple headers with the same key may present for the response.
  public var headers: [HttpHeader]

  /// The HTTP response body. If the body is not expected, it should be empty.
  public var body: Data

  /// Initialize a new instance of `HttpResponse`.
  public init(
    status: Int32 = Int32(),
    reason: String = String(),
    headers: [HttpHeader] = [],
    body: Data = Data(),
  ) {
    self.status = status
    self.reason = reason
    self.headers = headers
    self.body = body
  }
}
