// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudWkt

/// Represents an HTTP request.
public struct HttpRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The HTTP request method.
  public var method: String

  /// The HTTP request URI.
  public var uri: String

  /// The HTTP request headers. The ordering of the headers is significant.
  /// Multiple headers with the same key may present for the request.
  public var headers: [HttpHeader]

  /// The HTTP request body. If the body is not expected, it should be empty.
  public var body: Data

  /// Initialize a new instance of `HttpRequest`.
  public init(
    method: String = String(),
    uri: String = String(),
    headers: [HttpHeader] = [],
    body: Data = Data(),
  ) {
    self.method = method
    self.uri = uri
    self.headers = headers
    self.body = body
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.rpc.HttpRequest" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
