// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Provides a localized error message that is safe to return to the user
/// which can be attached to an RPC error.
public struct LocalizedMessage: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The locale used following the specification defined at
  /// https://www.rfc-editor.org/rfc/bcp/bcp47.txt.
  /// Examples are: "en-US", "fr-CH", "es-MX"
  public var locale: Swift.String

  /// The localized error message in the above locale.
  public var message: Swift.String

  /// Initialize a new instance of `LocalizedMessage`.
  public init(
    locale: Swift.String = Swift.String(),
    message: Swift.String = Swift.String(),
  ) {
    self.locale = locale
    self.message = message
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.rpc.LocalizedMessage" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
