// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudWkt

/// Describes what preconditions have failed.
///
/// For example, if an RPC failed because it required the Terms of Service to be
/// acknowledged, it could list the terms of service violation in the
/// PreconditionFailure message.
public struct PreconditionFailure: Codable, Equatable, GoogleCloudWkt._AnyPackable, Sendable {
  /// Describes all precondition violations.
  public var violations: [PreconditionFailure.Violation]

  /// Initialize a new instance of `PreconditionFailure`.
  public init(
    violations: [PreconditionFailure.Violation] = [],
  ) {
    self.violations = violations
  }

  /// A message type used to describe a single precondition failure.
  public struct Violation: Codable, Equatable, GoogleCloudWkt._AnyPackable, Sendable {
    /// The type of PreconditionFailure. We recommend using a service-specific
    /// enum type to define the supported precondition violation subjects. For
    /// example, "TOS" for "Terms of Service violation".
    public var type: String

    /// The subject, relative to the type, that failed.
    /// For example, "google.com/cloud" relative to the "TOS" type would indicate
    /// which terms of service is being referenced.
    public var subject: String

    /// A description of how the precondition failed. Developers can use this
    /// description to understand how to fix the failure.
    ///
    /// For example: "Terms of service not accepted".
    public var description: String

    /// Initialize a new instance of `Violation`.
    public init(
      type: String = String(),
      subject: String = String(),
      description: String = String(),
    ) {
      self.type = type
      self.subject = subject
      self.description = description
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.rpc.PreconditionFailure.Violation"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.rpc.PreconditionFailure"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
