// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudWkt

/// Describes how a quota check failed.
///
/// For example if a daily limit was exceeded for the calling project,
/// a service could respond with a QuotaFailure detail containing the project
/// id and the description of the quota limit that was exceeded.  If the
/// calling project hasn't enabled the service in the developer console, then
/// a service could respond with the project id and set `service_disabled`
/// to true.
///
/// Also see RetryInfo and Help types for other details about handling a
/// quota failure.
public struct QuotaFailure: Codable, Equatable, GoogleCloudWkt._AnyPackable {
  /// Describes all quota violations.
  public var violations: [QuotaFailure.Violation]

  /// Initialize a new instance of `QuotaFailure`.
  public init(
    violations: [QuotaFailure.Violation] = [],
  ) {
    self.violations = violations
  }

  /// A message type used to describe a single quota violation.  For example, a
  /// daily quota or a custom quota that was exceeded.
  public struct Violation: Codable, Equatable, GoogleCloudWkt._AnyPackable {
    /// The subject on which the quota check failed.
    /// For example, "clientip:<ip address of client>" or "project:<Google
    /// developer project id>".
    public var subject: String

    /// A description of how the quota check failed. Clients can use this
    /// description to find more about the quota configuration in the service's
    /// public documentation, or find the relevant quota limit to adjust through
    /// developer console.
    ///
    /// For example: "Service disabled" or "Daily Limit for read operations
    /// exceeded".
    public var description: String

    /// The API Service from which the `QuotaFailure.Violation` orginates. In
    /// some cases, Quota issues originate from an API Service other than the one
    /// that was called. In other words, a dependency of the called API Service
    /// could be the cause of the `QuotaFailure`, and this field would have the
    /// dependency API service name.
    ///
    /// For example, if the called API is Kubernetes Engine API
    /// (container.googleapis.com), and a quota violation occurs in the
    /// Kubernetes Engine API itself, this field would be
    /// "container.googleapis.com". On the other hand, if the quota violation
    /// occurs when the Kubernetes Engine API creates VMs in the Compute Engine
    /// API (compute.googleapis.com), this field would be
    /// "compute.googleapis.com".
    public var apiService: String

    /// The metric of the violated quota. A quota metric is a named counter to
    /// measure usage, such as API requests or CPUs. When an activity occurs in a
    /// service, such as Virtual Machine allocation, one or more quota metrics
    /// may be affected.
    ///
    /// For example, "compute.googleapis.com/cpus_per_vm_family",
    /// "storage.googleapis.com/internet_egress_bandwidth".
    public var quotaMetric: String

    /// The id of the violated quota. Also know as "limit name", this is the
    /// unique identifier of a quota in the context of an API service.
    ///
    /// For example, "CPUS-PER-VM-FAMILY-per-project-region".
    public var quotaId: String

    /// The dimensions of the violated quota. Every non-global quota is enforced
    /// on a set of dimensions. While quota metric defines what to count, the
    /// dimensions specify for what aspects the counter should be increased.
    ///
    /// For example, the quota "CPUs per region per VM family" enforces a limit
    /// on the metric "compute.googleapis.com/cpus_per_vm_family" on dimensions
    /// "region" and "vm_family". And if the violation occurred in region
    /// "us-central1" and for VM family "n1", the quota_dimensions would be,
    ///
    /// {
    ///   "region": "us-central1",
    ///   "vm_family": "n1",
    /// }
    ///
    /// When a quota is enforced globally, the quota_dimensions would always be
    /// empty.
    public var quotaDimensions: [String: String]

    /// The enforced quota value at the time of the `QuotaFailure`.
    ///
    /// For example, if the enforced quota value at the time of the
    /// `QuotaFailure` on the number of CPUs is "10", then the value of this
    /// field would reflect this quantity.
    public var quotaValue: Int64

    /// The new quota value being rolled out at the time of the violation. At the
    /// completion of the rollout, this value will be enforced in place of
    /// quota_value. If no rollout is in progress at the time of the violation,
    /// this field is not set.
    ///
    /// For example, if at the time of the violation a rollout is in progress
    /// changing the number of CPUs quota from 10 to 20, 20 would be the value of
    /// this field.
    public var futureQuotaValue: Int64?

    /// Initialize a new instance of `Violation`.
    public init(
      subject: String = String(),
      description: String = String(),
      apiService: String = String(),
      quotaMetric: String = String(),
      quotaId: String = String(),
      quotaDimensions: [String: String] = [:],
      quotaValue: Int64 = Int64(),
      futureQuotaValue: Int64? = nil,
    ) {
      self.subject = subject
      self.description = description
      self.apiService = apiService
      self.quotaMetric = quotaMetric
      self.quotaId = quotaId
      self.quotaDimensions = quotaDimensions
      self.quotaValue = quotaValue
      self.futureQuotaValue = futureQuotaValue
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.rpc.QuotaFailure.Violation"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.rpc.QuotaFailure" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
