// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Contains metadata about the request that clients can attach when filing a bug
/// or providing other forms of feedback.
public struct RequestInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// An opaque string that should only be interpreted by the service generating
  /// it. For example, it can be used to identify requests in the service's logs.
  public var requestId: Swift.String

  /// Any data that was used to serve this request. For example, an encrypted
  /// stack trace that can be sent back to the service provider for debugging.
  public var servingData: Swift.String

  /// Initialize a new instance of `RequestInfo`.
  public init(
    requestId: Swift.String = Swift.String(),
    servingData: Swift.String = Swift.String(),
  ) {
    self.requestId = requestId
    self.servingData = servingData
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.rpc.RequestInfo" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
