// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The `Status` type defines a logical error model that is suitable for
/// different programming environments, including REST APIs and RPC APIs. It is
/// used by [gRPC](https://github.com/grpc). Each `Status` message contains
/// three pieces of data: error code, error message, and error details.
///
/// You can find out more about this error model and how to work with it in the
/// [API Design Guide](https://cloud.google.com/apis/design/errors).
public struct Status: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The status code, which should be an enum value of
  /// [google.rpc.Code][google.rpc.Code].
  ///
  /// [google.rpc.Code]: <doc:Code>
  public var code: Swift.Int32

  /// A developer-facing error message, which should be in English. Any
  /// user-facing error message should be localized and sent in the
  /// [google.rpc.Status.details][google.rpc.Status.details] field, or localized
  /// by the client.
  ///
  /// [google.rpc.Status.details]: <doc:Status/details>
  public var message: Swift.String

  /// A list of messages that carry the error details.  There is a common set of
  /// message types for APIs to use.
  public var details: [GoogleCloudWkt.`Any`]

  /// Initialize a new instance of `Status`.
  public init(
    code: Swift.Int32 = Swift.Int32(),
    message: Swift.String = Swift.String(),
    details: [GoogleCloudWkt.`Any`] = [],
  ) {
    self.code = code
    self.message = message
    self.details = details
  }

  public static var _anyTypeUrl: String { return "type.googleapis.com/google.rpc.Status" }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
